### ISSUE TITLE
Add a {{ yaml }} helper

### ISSUE THREAD

**Issue by lodejard** [Microsoft/Atlas#40]
Should work like the `{{ json [expr] }}` helper, where the first non-null expr is evaluation is serialized

Should also accept an option like `{{ yaml [expr] indent=10 }}` because yaml is sensitive to indentation.

The very first line will probably be an issue... Might not want to indent the very first line. Or might want to include a leading newline character to ensure every non-empty line has the same indentation.

Leading newline might be the way to go, actually, because that will also enable the helper to be used on a single line. That is to say, both of the following examples would have the same effect.
```
something:
  another: 
    {{ yaml foo indent=4 }}  
```
```
something:
  another: {{ yaml foo indent=4 }}  
```

**Comment by HrushikeshBodas** [comment]
Can I get a guide on how to solve this? I am new to Ms opensource. Any help is appreciated

**Comment by lodejard** [comment]
Hi @HrushikeshBodas - thanks for taking an interest in this!

So... Let's see... Most of this change will be making a YamlHelper function right next to the existing JsonHelper one.

Here is where you'd add a "yaml", YamlHelper line to the list of custom helpers:
https://github.com/Microsoft/Atlas/blob/5735b88baa740f0fc72dd75cb039b93fe8f453f6/src/Microsoft.Atlas.CommandLine/Templates/TemplateEngine.cs#L35

Here is the JsonHelper function, you'd add one called calls YamlHelper which calls ToYamlString instead of ToJsonString.
https://github.com/Microsoft/Atlas/blob/5735b88baa740f0fc72dd75cb039b93fe8f453f6/src/Microsoft.Atlas.CommandLine/Templates/TemplateEngine.cs#L221

Here is the ToJsonString function, you'd add another one called ToYamlString which uses `Services.Serializers.YamlSerializer.Serialize` instead of `Services.Serializers.JsonSerializer.Serialize` 
https://github.com/Microsoft/Atlas/blob/5735b88baa740f0fc72dd75cb039b93fe8f453f6/src/Microsoft.Atlas.CommandLine/Templates/TemplateEngine.cs#L291

To check if that's working you'll probably want to make a temporary folder with a small workflow:

`try-it/values.yaml`
```
car:
  name: "My car"
  wheels: 4
  runs: true
```
`try-it/workflow.yaml`
```
operations:
- output:
    car-to-json: {{{ json car }}}

- output:
    car-to-yaml: {{{ yaml car indent=6 }}}
```
`./atlas.sh deploy try-it`

It probably won't load correctly - but it should write an `_output/workflow.yaml` file to see what you get. It'll probably look like this:

```
operations:
- output:
    car-to-json: {"name": "My car", "wheels": 4, "runs": true}

- output:
    car-to-yaml: name: My car
wheels: 4
runs: true
```

This last bit is probably going to be the tricky part. In the ToYamlString function you'll want to add an `int indent` parameter. Basically - instead of just returning what was serialized - you'd need to split the string into an array of lines, then prefix each line with Environment.NewLine + new string(' ', indent), then rejoin them all into a single string to return.

The result you're looking for is a generated workflow which looks like this:
```
operations:
- output:
    car-to-json: {"name": "My car", "wheels": 4, "runs": true}

- output:
    car-to-yaml: 
      name: My car
      wheels: 4
      runs: true
```
