### ISSUE TITLE
Need an operation-level foreach property

### ISSUE THREAD

**Issue by lodejard** [Microsoft/Atlas#71]
Should work like `values` but anything which evaluates to an array would cause the operation to run once for each array item. 

Example usage:
```
operations:
- message: Listing subscriptions
  request: apis/azure/subscriptions-list.yaml
  output:
    subscriptions: (result.body.value)

- foreach:
    azure:
      subscription: (subscriptions[].subscriptionId)
  message: (['Listing resource groups in ', azure.subscription])
  request: apis/azure/resourcegroups-list.yaml
  output:
    results:
      (azure.subscription):
        resourceGroups: (result.body.value)
```
