### ISSUE TITLE
Need to be able to jmespath query values and output keys as well

### ISSUE THREAD

**Issue by lodejard** [Microsoft/Atlas#72]
When looping over data and adding values to a hash table it's very tricky to build that property-object relationship using to_object.

Better would be to be able to jmespath query property names in the same way as values. 

```
  output:
    results:
      "(azure.subscription)":
        resourceGroups: (result.body.value)
```

The query will need to result in a single string - if it is anything complex there's no way to know how to map what parts of the complex key should associate with what parts of the complex value.

Oh... I take that back. If the key results in an array of string and the value results in an equally sized array, it would be possible to use that information to turn it into a hash object.

```
  output:
    result:
      (result.body.value.id): (result.body.value)
```
