### ISSUE TITLE
Workflow should generate request yaml files from swagger

### ISSUE THREAD

**Issue by lodejard** [Microsoft/Atlas#81]
Declaring request yaml can be inconvenient. Would be better to declare swagger file references which will auto-generated a request yaml file per operationId.

``` yaml
generate:
  swagger:
    {apis/path/prefix}: 
    - paths/to/swaggers.json
    - paths/to/folders[/readme.md] 
```

Swagger has a convention of `title` is client name and `operationId` is method name. So the generated files will have the effective path 

```
api/path/prefix/title/operationId.yaml
```
