### ISSUE TITLE
Load workflow metadata from readme.md yaml

### ISSUE THREAD

**Issue by lodejard** [Microsoft/Atlas#82]
Based on the autorest technique of using the readme.rm file as both documentation, description, and packaging metadata.

``` yaml
author: string
license: path
dependencies:
  swagger: { <mount-path> : [<swagger-reference>] }
  packages: { <mount-path>: <package-reference> }
```
